### ISSUE TITLE
Issues about the logo : misdirection and version

### ISSUE THREAD

**Issue by mdrutel** [TOSIT-IO/tdp-website#6]
Hi,

There are 2 issues about the logo on the top left :

- When you click on the logo, we are redirected to https://tosit-io.github.io/tdp-website.txt
- The logo is not from the last version

**Comment by wdavidw** [comment]
Thanks for noticing. I got this version from Edouard many months ago. I don't have any other one. If you have a later version at your disposal in SVG, please replace it. The location is `src/app/[lang]/(pages)/[...slug]/layout/assets/LogoColorLight.svg`.

**Comment by wdavidw** [comment]
Could you share the logo if the one in use is not the one expected?

**Comment by wdavidw** [comment]
Note, the redirection was fixed after the latest dependencies update.

**Comment by wdavidw** [comment]
This issue is in fact 2 issues. The first one about the redirection has been solved for some time and the second about the correct log has no answer at the moment. Closing now. If the second issue is still valid, then it deserves its own issue.
